local L = IGAS:NewLocale("IGAS_Toolkit")--, "zhTW")
if not L then return end

L["Toolkit Manager"] = "工具集管理箱"
L["Toolkit"] = "工具集"
L["Enable"] = "啟用"
L["Disable"] = "停用"
L["Using"] = "使用中"
L["Discard"] = "廢棄"
L[" - Stoped"] = IGAS.System.Widget.FontColor.RED .. "[停用中]"

L["AutoQuest"] = "自動任務"
L["Accept All"] = "接受所有任務"
L["Not auto return special quest"] = "不自動完成特定的任務"

L["AutoRepair"] = "自動修理"
L["Check Reputation"] = "檢查聲望"
L["[AutoRepair] No enough money to repair."] = "[自動修理]沒有足夠的資金修理."
L["[AutoRepair] Cost [Guild] %s."] = "[自動修理]消耗[工會] %s."
L["[AutoRepair] Cost %s."] = "[自動修理]消耗 %s."

L["AutoBuy"] = "自動購買"
L["Buy Item"] = "購買物品"
L["Click to remove"] = "點擊物品來移除記錄。"
L["Okay"] = "確認"
L["Cancel"] = "取消"

L["AutoSell"] = "自動販賣"
L["[AutoSell] Buy back item if you don't want auto sell it next time."] = "[自動販賣] 如果不想下次自動販賣的物品，請購回。"
L["[AutoSell] Sell Item List:"] = "[自動販賣] 販賣物品清單:"
L["[AutoSell] %s for %s."] = "[自動販賣] %s 獲得 %s."
L["[AutoSell] %s * %d for %s."] = "[自動販賣] %s * %d 獲得 %s."
L["[AutoSell] Total : %s."] = "[自動販賣] 共計 : %s."
L["Sell Uncommon Equipment(SouldBound)"] = "販賣綠色裝備(已綁定)"
L["Sell Uncommon Equipment(Not SouldBound)"] = "販賣綠色裝備(未綁定)"
L["Sell Rare Equipment(SouldBound)"] = "販賣藍色裝備(已綁定)"
L["Sell Rare Equipment(Not SouldBound)"] = "販賣藍色裝備(未綁定)"

L["EasyMail"] = "郵件助手"
L["Recent"] = "最近聯繫人"
L["Character"] = "角色"
L["Friend"] = "好友"
L["Guild"] = "工會"
L["Send same type material"] = "發送同類物品"

L["HightLightItem"] = "高亮物品"

L["AutoShowChatFrameLink"] = "自動顯示聊天欄的物品鏈接"
L["Show item"] = "顯示物品"
L["Show spell"] = "顯示法術"
L["Show enchant"] = "顯示附魔"
L["Show quest"] = "顯示任務"
L["Show talent"] = "顯示天賦"
L["Show glyph"] = "顯示雕文"
L["Show achievement"] = "顯示成就"

L["AuctionHelper"] = "拍賣行助手"
L["Gem Helper"] = "寶石搜索助手"
L["Glyph Helper"] = "雕文搜索助手"
L["Clear"] = "清除"
L["Scan"] = "掃描"
L["It's the first time you using the gem helper, \n do you want to scan now?"] = "這是您第一次使用寶石搜索,\n是否現在開始掃描數據?"
L["Show Search History"] = "顯示最近搜索清單"
L["Show Gem Helper"] = "顯示寶石搜索助手"
L["Show Glyph Helper"] = "顯示雕文搜索助手"
L["Scan abort! please try later."] = "掃描終止!請等待一段時間再嘗試。"
L["Please input the split characters for gem property."] = "請手動輸入多屬性寶石屬性的間隔文字。"
L["Gem scan finished, thanks for waiting."] = "寶石掃描結束，感謝您的等待。"

L["AdditionalCommand"] = "額外命令"

L["GlyphReminder"] = "雕文提醒"
L["Needed By"] = "有需求"
L["Reset"] = "重置"

L["PetWatch"] = "寵物數據檢索"
L["Show collected pet"] = "顯示已收集野外寵物"
L["Show not collected pet"] = "顯示未收集野外寵物"

L["WorldMapScale"] = "世界地圖縮放記錄"